AY2425S2-CS2103T-F13-1/tp

docs/AboutUs.md
docs/team/golddirio.md

Update AboutUs.md and add golddirio.md

Update AboutUs page

---

docs/AboutUs.md

Fixes to ensure website-adapted checks pass, changes made are to AboutUs.md to ensure naming conventions of images match and formatting is A-okay.

Fix naming issues for AboutUs

---

src/main/java/seedu/address/logic/commands/FilterNoteCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/FilterNoteCommandParser.java
src/test/java/seedu/address/logic/commands/FilterNoteCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/FilterNoteCommandParserTest.java

Add filternote command to filter out the notes by title
- Command: filternote [index] nt/[title]
For all the notes belonged to index patient, those matching the keyword title will be displayed. 
Closes #58

Add filter note by title

---

src/main/java/seedu/address/logic/commands/NoteCommand.java
src/main/java/seedu/address/logic/parser/NoteCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/note/Note.java

resolve #53 
when attempting to add an invalid note, an error is shown instead of no action happening previously

Add warning when note to add is invalid

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/ui/CommandBox.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/CommandBox.fxml
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml

- **Text wrap** for command input text box
- **Dynamic resizing** of command input text box, to match the amount of text inside
* Changed TextField to TextArea, as TextField doesn't allow text wrap
* Add eventFilter to TextField, which will invoke `handleCommandEntered()` whenever `enter` key is pressed. Prevents default behaviour of adding a new line
* Added styling to DarkTheme.css to match the styling of the rest of the app
* Modified components in MainWindow.fxml to use VBox with vgrow, to enable dynamic resizing of all components as the command input box grows or shrinks
Code Coverage will fail because I'm not able to write tests for UI components without TestFX, which is not required for this tP. Other than that, there should be no issues!

Enhance command box UI

---

docs/UserGuide.md
src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/NoteCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/model/patient/Address.java
src/main/java/seedu/address/model/patient/Email.java
src/main/java/seedu/address/model/patient/Name.java
src/main/java/seedu/address/model/patient/Patient.java
src/main/java/seedu/address/model/patient/Phone.java
src/main/java/seedu/address/model/tag/Tag.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java

Add the following commands and some examples to our user guide:
-     View Notes
-     Filter Notes
-     Add Notes
-     Edit Notes
-     Delete Notes
Closes #49

Add notes to user guide

---

docs/UserGuide.md

Simple edit to update the link to our product releases page.

Fix Neurosync Relases link

---

docs/diagrams/ArchitectureSequenceDiagram.puml
docs/diagrams/BetterModelClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml

Remove Email from Model and Renamed User as Psychiatrist

---

docs/UserGuide.md

Add page breaks to ensure the PDF format of the userguide is clearer

Add page breaks

---

docs/UserGuide.md

Reorder pagebreaks for clearer and more consistent page formatting

Modify page breaks

---

docs/UserGuide.md

remove empty page 8, remove "back to top" button and `---` separator from table of contents

Remove empty page

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/RedoCommandTest.java
src/test/java/seedu/address/logic/commands/UndoCommandTest.java
src/test/java/seedu/address/model/VersionedAddressBookTest.java

Add tests for undo/redo

---

docs/DeveloperGuide.md
docs/UserGuide.md

Rearrange dg

---

docs/DeveloperGuide.md

Update Table of Contents

---

docs/DeveloperGuide.md
src/main/java/seedu/address/logic/commands/EditNoteCommand.java
src/main/java/seedu/address/logic/parser/EditNoteCommandParser.java

Removed the issue of duplicate nt/ nc/ prefixes
Added error message to make sure user index is 8 digits or less
Closes #153 
Closes #151
Closes #150

Rearrange DG and Fixed Bugs in EditNoteCommand

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
src/main/java/seedu/address/logic/commands/EditNoteCommand.java
src/main/java/seedu/address/logic/commands/FilterNoteCommand.java

I have fixed #141 #142 #143 
Also for #152 I perfect the message for invalid range.

Fix alpha bugs

---

docs/DeveloperGuide.md
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/FilterNoteCommand.java

Clean up DG (some parts have "to be updated")

Fix some minor standardization issues

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/FilterNoteCommand.java
src/main/java/seedu/address/logic/commands/NoteCommand.java
src/main/java/seedu/address/model/note/Note.java
src/main/java/seedu/address/storage/JsonAdaptedNote.java
src/main/java/seedu/address/storage/JsonAdaptedPatient.java
src/main/java/seedu/address/storage/JsonAdaptedTag.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/NoteCommandTest.java
src/test/java/seedu/address/model/note/NoteTest.java

- Note.java
- NoteCommand.java
- NoteTest.java and NoteCommandTest.java
- JsonAdaptedNote.java
---
- Help Command
- Add patient command
- JsonAdaptedPatient.java
- JsonAdaptedTag.java
---
- Tag.java
- DuplicatePatientException.java (model/patient/exception)
- PatientNoteFormatter.java
---
- AddressBookParser.java
- AddressBookStorage.java
Resolves #146, #140, #162
Closes #117

Code cleanup

---

docs/UserGuide.md

Reformat to remove near empty pages when converted to PDF format

Fix user guide formatting

---

docs/DeveloperGuide.md

Added a plan to enhance MVVM models
Closes #190

Add Planned Enhancements
